[telegram]
token = "1699062794:AAEjuMPyl6VZHqpEvec4i-PAx9sEITOjRk8
"
workers = 1
admins = [563239385]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
